# Generated by Django 3.0.5 on 2020-05-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200519_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=111)),
                ('address', models.CharField(max_length=111)),
                ('zip_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
            ],
        ),
    ]
